{% set data = load_setup_py_data() %}

package:
  name: anyqt
  version: {{ data['version'] }}

source:
  git_url: ../

build:
  number: 0

  script:
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyqt

test:
  imports:
    - AnyQt.QtCore
    - AnyQt.QtGui
    - AnyQt.QtWidgets
    - AnyQt.QtNetwork
    - AnyQt.QtSvg

about:
  home: https://github.com/ales-erjavec/anyqt/
  license: GPL-3.0
  license_family: GPL3
  summary: PyQt4/PyQt5 compatibility layer.
  doc_url: http://anyqt.readthedocs.io/en/latest
  dev_url: https//github.com/ales-erjavec/anyqt
